In [1]:
import pandas as pd
import os

### Change to root directory

In [ ]:
os.getcwd()
os.chdir('..')

'/home/vijay/Desktop/House-Price-Prediction/notebook'

### loading data

In [5]:
df = pd.read_csv('data/Housing.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21613 non-null  int64
 1   date           21613 non-null  str
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64
 6   sqft_lot       21613 non-null  int64
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64
 9   view           21613 non-null  int64
 10  condition      21613 non-null  int64
 11  grade          21613 non-null  int64
 12  sqft_above     21613 non-null  int64
 13  sqft_basement  21613 non-null  int64
 14  yr_built       21613 non-null  int64
 15  yr_renovated   21613 non-null  int64
 16  zipcode        21613 non-null  int64
 17  lat            21613 non-null  float64
 18  long           21613 non-null  float64
 19  sqft_living15  21613 non-null  int64
 20  sqft_lot15     21613 non-null  int64
dtypes: float64(5), int64(15), str(1)
memory usage: 3.5 MB

In [6]:
df.head(10)

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7229300521,20141013T000000,231300.0,2,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
5,7237550310,20140512T000000,1225000.0,4,4.50,5420,101930,1.0,0,0,...,11,3890,1530,2001,0,98053,47.6561,-122.005,4760,101930
6,1321400060,20140627T000000,257500.0,3,2.25,1715,6819,2.0,0,0,...,7,1715,0,1995,0,98003,47.3097,-122.327,2238,6819
7,2008000270,20150115T000000,291850.0,3,1.50,1060,9711,1.0,0,0,...,7,1060,0,1963,0,98198,47.4095,-122.315,1650,9711
8,2414600126,20150415T000000,229500.0,3,1.00,1780,7470,1.0,0,0,...,7,1050,730,1960,0,98146,47.5123,-122.337,1780,8113
9,3793500160,20150312T000000,323000.0,3,2.50,1890,6560,2.0,0,0,...,7,1890,0,2003,0,98038,47.3684,-122.031,2390,7570

#### Remove unwanted
here :
1. id
2. date
3. sqft_lot
4. view
5. waterfront
6. zipcode	
7. yr_renovated
8. lat
9. long

In [9]:
df = df.drop(['id','date','sqft_lot', 'view', 'waterfront','zipcode','yr_renovated', 'lat', 'long'], axis=1)

In [10]:
df.head()

,price,bedrooms,bathrooms,sqft_living,floors,condition,grade,sqft_above,sqft_basement,yr_built,sqft_living15,sqft_lot15
0,231300.0,2,1.00,1180,1.0,3,7,1180,0,1955,1340,5650
1,538000.0,3,2.25,2570,2.0,3,7,2170,400,1951,1690,7639
2,180000.0,2,1.00,770,1.0,3,6,770,0,1933,2720,8062
3,604000.0,4,3.00,1960,1.0,5,7,1050,910,1965,1360,5000
4,510000.0,3,2.00,1680,1.0,3,8,1680,0,1987,1800,7503

In [11]:
df.isnull().sum()

price            0
bedrooms         0
bathrooms        0
sqft_living      0
floors           0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [14]:
df = df.drop_duplicates()

In [15]:
df.info()

<class 'pandas.DataFrame'>
Index: 21596 entries, 0 to 21612
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   price          21596 non-null  float64
 1   bedrooms       21596 non-null  int64
 2   bathrooms      21596 non-null  float64
 3   sqft_living    21596 non-null  int64
 4   floors         21596 non-null  float64
 5   condition      21596 non-null  int64
 6   grade          21596 non-null  int64
 7   sqft_above     21596 non-null  int64
 8   sqft_basement  21596 non-null  int64
 9   yr_built       21596 non-null  int64
 10  sqft_living15  21596 non-null  int64
 11  sqft_lot15     21596 non-null  int64
dtypes: float64(3), int64(9)
memory usage: 2.1 MB

In [16]:
df.describe()

,price,bedrooms,bathrooms,sqft_living,floors,condition,grade,sqft_above,sqft_basement,yr_built,sqft_living15,sqft_lot15
count,2.159600e+04,21596.000000,21596.000000,21596.000000,21596.000000,21596.000000,21596.000000,21596.000000,21596.000000,21596.000000,21596.000000,21596.000000
mean,5.401525e+05,3.370856,2.114535,2080.150630,1.493726,3.409567,7.656603,1788.480645,291.669985,1970.986711,1986.773893,12775.761761
std,3.672498e+05,0.929833,0.769997,918.525134,0.539584,0.650801,1.175685,828.132098,442.688109,29.369485,685.494521,27313.486139
min,7.500000e+04,0.000000,0.000000,290.000000,1.000000,1.000000,1.000000,290.000000,0.000000,1900.000000,399.000000,651.000000
25%,3.215000e+05,3.000000,1.750000,1430.000000,1.000000,3.000000,7.000000,1190.000000,0.000000,1951.000000,1490.000000,5100.000000
50%,4.500000e+05,3.000000,2.250000,1910.000000,1.500000,3.000000,7.000000,1560.000000,0.000000,1975.000000,1840.000000,7620.000000
75%,6.450000e+05,4.000000,2.500000,2550.000000,2.000000,4.000000,8.000000,2210.000000,560.000000,1997.000000,2360.000000,10087.000000
max,7.700000e+06,33.000000,8.000000,13540.000000,3.500000,5.000000,13.000000,9410.000000,4820.000000,2015.000000,6210.000000,871200.000000

In [18]:
import matplotlib.pyplot as plt

In [19]:
x = df.drop('price', axis=1)
y = df['price']

In [23]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error

In [24]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)
len(x_train), len(x_test), len(y_train), len(y_test)

(17276, 4320, 17276, 4320)

In [25]:
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [26]:
y_preds = model.predict(x_test)

In [31]:
print(f'Accuracy score : {r2_score(y_test, y_preds)}')
print(f'MAE : {mean_absolute_error(y_test, y_preds)}')

Accuracy score : 0.6153016520523644
MAE : 148714.54654471227

In [32]:
from sklearn.ensemble import RandomForestRegressor

In [38]:
model2 = RandomForestRegressor(n_estimators=200, random_state=42)
model2.fit(x_train, y_train)
y_preds2 = model2.predict(x_test)
print(f'MAE : {mean_absolute_error(y_test, y_preds2)}')

MAE : 120964.64486752462

In [39]:
import tensorflow as tf

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1778935648.411660  600175 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1778935648.413581  600175 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
I0000 00:00:1778935648.505530  600175 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1778935650.080773  600175 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1778935650.081195  600175 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.

In [43]:
len(x_train)

17276

In [45]:
x_train.ndim

2

In [ ]:
model = tf.keras.Sequential([
    tf.keras.layers.
])